config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  devise_for :users
root 'pages_controller#home'

end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :account
  after_create :build_account, :send_registration_mail

   def build_account
     Account.create(user: self) # Associations must be defined correctly for this syntax, avoids using ID's directly.
   end

   def send_registration_mail
     UserMailer.registration_mail(self).deliver_now
   end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  require 'carrierwave/orm/activerecord' # For image uploading

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to root_path, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find_by('user_id', params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:first_name, :last_name, :image, :adress, :phone, :website)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def determine_layout
      user_signed_in? ? "application" : "landing_page"
    end

end

app/controllers/controlpanel_controller.rb
class ControlpanelController < ApplicationController
  before_action :authenticate_user!

  def index
  end

end

app/controllers/pages_controller_controller.rb
class PagesControllerController < ApplicationController

  layout :determine_layout

  def home
    render 'controlpanel/index' if user_signed_in?
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(base = '')
    page_title = "Young Creatives At Your Service!"
    if base.empty?
      page_title
    else
      base + " | " + page_title
    end
  end

  def get_full_name(account)
    return account.first_name + " " + account.last_name
  end
  
end

app/helpers/controlpanel_helper.rb
module ControlpanelHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/views/accounts/_form.html.haml
.sixteen.wide.column
  .ui.form.error
    = form_for @account do |f|
      - if @account.errors.any?
        #error_explanation
          %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
          %ul
            - @account.errors.full_messages.each do |msg|
              %li= msg

      .field
        = f.label :first_name
        = f.text_field :first_name

      .field
        = f.label :last_name
        = f.text_field :last_name

      .field
        = f.label :adress
        = f.text_field :adress

      .field
        = f.label :phone
        = f.text_field :phone

      .field
        = f.label :website
        = f.text_field :website

      .field
        = f.label :image
        = f.file_field :image

      .actions
        = f.submit 'Update Profile', class: 'ui button positive'

app/views/accounts/edit.html.haml
%h1 Edit Profile

= render 'form'

app/views/accounts/index.html.haml
%h1 Listing accounts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= link_to 'Show', account
        %td= link_to 'Edit', edit_account_path(account)
        %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Account', new_account_path

app/views/accounts/show.html.haml
.column
  .ui.segment
    .ui.two.column.grid
      .column
        .ui.card
          = image_tag @account.image, alt: "", class: "ui big image visible content"

app/views/controlpanel/index.html.haml
.ui.vertical.strip.segment
  .ui.middle.aligned.stackable.grid.container
    .row
      .four.wide.column
        = link_to edit_user_registration_path(current_user) do
          %h4.ui.center.aligned.icon.header
            %i.setting.icon
            .content
              Inställningar
              .sub.header Hantera dina inställningar

      .four.wide.column
        = link_to edit_account_path(current_user) do
          %h4.ui.center.aligned.icon.header
            %i.user.icon
            .content
              Profil
              .sub.header Hantera din profil

      .four.wide.column
        = link_to account_path(current_user) do
          %h4.ui.center.aligned.icon.header
            %i.spy.icon
            .content
              Min Sida
              .sub.header Visa din profil

      .four.wide.column
        = link_to "#" do
          %h4.ui.center.aligned.icon.header
            %i.game.icon
            .content
              Mina Projekt
              .sub.header Visa dina projekt

app/views/layouts/application.html.haml
!!! 5
%head
  %title= page_title(yield(:title))
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag 'dist/semantic.min.css', media: 'all'
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag 'dist/semantic.min.js', 'data-turbolinks-track' => true
  = javascript_include_tag 'app.js'
  = csrf_meta_tags

%body
  =render 'layouts/navigation/auth/base_application_navigation'
  = yield
  =render 'layouts/footers/base_footer'

app/views/layouts/footers/_base_footer.html.haml
.ui.inverted.vertical.footer.segment
  .ui.container
    .ui.stackable.inverted.divided.equal.height.stackable.grid
      .three.wide.column
        %h4.ui.inverted.header
          About
        .ui.inverted.link.list
          %a.item The Company
          %a.item Founders
          %a.item Vision
          %a.item Investment
      .three.wide.column
        %h4.ui.inverted.header
          Services
        .ui.inverted.link.list
          %a.item Orders
          %a.item Pricing
          %a.item FAQ
          %a.item Legal
      .seven.wide.column
        %h4.ui.inverted.header
          Follow us on social media
        .ui.inverted.horizontal.list
          .item
            %button.ui.circular.facebook.icon.button
              %i.facebook.icon
          .item
            %button.ui.circular.twitter.icon.button
              %i.twitter.icon
          .item
            %button.ui.circular.google.plus.icon.button
              %i.google.plus.icon
          .item
            %button.ui.circular.linkedin.icon.button
              %i.linkedin.icon

app/views/layouts/landing_page.html.haml
!!! 5
%head
  %title= page_title(yield(:title))
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = stylesheet_link_tag 'dist/semantic.min.css', media: 'all'
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = javascript_include_tag 'dist/semantic.min.js', 'data-turbolinks-track' => true
  = javascript_include_tag 'app.js'
  = csrf_meta_tags

%body
  -#=render 'layouts/navigation/base_navigation'
  =render 'layouts/navigation/base_sidebar_navigation'

  .ui.pusher
    =render 'layouts/navigation/base_application_navigation'
    = yield
    =render 'layouts/footers/base_footer'

app/views/layouts/navigation/_base_application_navigation.html.haml
.ui.vertical.segment
  .ui.container
    .ui.large.secondary.menu
      .ui.header.item
        = link_to 'YoungCreatives', '/'
      %a.item Start
      %a.item Om oss
      %a.item Priser
      %a.item Kontakt
      .right.menu
      -if user_signed_in?
        .item
          .ui.small.primary.button
        = link_to "Log out", destroy_user_session_path, method: :delete
        .item
          .ui.small.primary.button
        = link_to current_user.email, edit_user_registration_path
        .item
          .ui.small.primary.button
        = link_to "", "/admin"
      -else
        .item
          = link_to "Logga in", new_user_session_path, class: 'ui small primary button'
        .item
          = link_to "Registrera", new_user_registration_path, class: 'ui small secondary button'

app/views/pages_controller/home.html.haml
.ui.inverted.vertical.masthead.center.aligned.segment
  .ui.text.container
    %h1.ui.inverted.header
      Hitta ditt nya jobb idag!
    %h2
      Sidan för kreative töntar som dig
    .ui.huge.primary.button
      Läs mer
      %i.right.arrow.icon

.ui.vertical.strip.segment
  .ui.middle.aligned.stackable.grid.container
    .row
      .eight.wide.column
        %h3.ui.header
          Something special for your team
        %p
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Mauris sagittis ut mi auctor posuere. Nam scelerisque interdum turpis sit amet laoreet. Quisque ex erat, interdum ut consectetur in, porta quis dolor. Quisque vitae nisl imperdiet nulla elementum convallis vel non diam.
        %h3.ui.header
          And we promise it will work
        %p
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ut mi auctor posuere. Nam scelerisque interdum turpis sit amet laoreet. Quisque ex erat, interdum ut consectetur in, porta quis dolor. Quisque vitae nisl imperdiet nulla elementum convallis vel non diam.
      .six.wide.right.floated.column
        = image_tag("smile.jpeg", class: "ui large bordered rounded image")
    .row
      .center.aligned.column
        %a.ui.huge.primary.button
          Check it out!

.ui.vertical.stripe.segment
  .ui.text.container
    %h3.ui.header
      Breaking The Grid, Grabs Your Attention
    %p
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ut mi auctor posuere.
    %a.ui.large.positive.button
      Read More
    %h4.ui.horizontal.header.divider
      %a
        Even more so
    %h3.ui.header
      Our Customers are super happy
    %p
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis ut mi auctor posuere.
    %a.ui.large.positive.button
      Im still interested